apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: spot-termination-notice-handler
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: spot-termination-notice-handler
      name: spot-termination-notice-handler
    spec:
      serviceAccount: spot-termination-handler
      serviceAccountName: spot-termination-handler
      containers:
      - image: mumoshu/kube-spot-termination-notice-handler:1.7.0-0.9.2
        imagePullPolicy: IfNotPresent
        name: spot-termination-notice-handler
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spot-termination-handler
roleRef:
  kind: ClusterRole
  name: spot-termination-handler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: spot-termination-handler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: spot-termination-handler
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-termination-handler
  namespace: kube-system
